Modify Docker
aidudezzz/deepbots pull request #123
Opened 2022-12-16 14:05 UTC by KelvinYang0320

- [x] Update Dockerfile for generic requirements
  - [x] From Docker Image: cyberbotics/webots
  - [x] Install ubuntu libraries
  - [x] Install deepbots
  - [ ] Install miniconda?
- [x] Check docker with cpu
- [ ] Check docker with gpu
- [ ] Pull from DockerHub aidudezzz/deepbots

2022-12-24 11:48 UTC, KelvinYang0320 commented
DockerHub: https://hub.docker.com/u/aidudezzz

2022-12-24 13:10 UTC, tsampazk requested changes
Thanks @KelvinYang0320, really good job on the docker!

I have some mostly minor comments, also could we change all the occurrences of `docker` to either `Docker` or `docker`? The capitalization of the first letter is a bit inconsistent between the section heads and the text.

I haven't done any running of the instructions yet, i'll go ahead and test it as a follow-up.

2022-12-24 13:10 UTC, tsampazk commented on docker/README.md
> +   ```
As i don't have a lot of experience with docker i'm a little confused by this. Specifically with `<user-name>/<repo-name>`, at what does this refer to? Could we maybe provide an example?

2022-12-24 13:10 UTC, tsampazk commented on docker/README.md
> +   * tag: https://hub.docker.com/r/aidudezzz/deepbots
I think you meant to link to the tags tab:
```suggestion
   * available tags: https://hub.docker.com/r/aidudezzz/deepbots/tags
```
Also instead of tag->available tags might sound better

2022-12-24 13:10 UTC, tsampazk commented on docker/README.md
> +   * tag: https://hub.docker.com/r/aidudezzz/deepbots-conda/tags
```suggestion
   * available tags: https://hub.docker.com/r/aidudezzz/deepbots-conda/tags
```

2022-12-24 13:10 UTC, tsampazk commented on docker/README.md
> +   $ docker pull aidudezzz/deepbots:<tag>
Similar to the previous comment, do you think could we provide an example of a complete link including a tag, so it is really clear to what the user should do?

2022-12-25 01:50 UTC, KelvinYang0320 commented on docker/README.md
> +   * tag: https://hub.docker.com/r/aidudezzz/deepbots
Thanks!

2022-12-25 02:02 UTC, KelvinYang0320 commented on docker/README.md
> +   ```
`-t`: Name and optionally a tag in the 'name:tag' format
* ref: https://docs.docker.com/engine/reference/commandline/build/#options

Actually, users can name their image as `<image-name>`  instead of `<user-name>/<repo-name>`.
`<user-name>/<repo-name>` is for dockerhub users.
I will update it to make it clear. 😄

2022-12-26 16:31 UTC, KelvinYang0320 commented on docker/README.md
@tsampazk Yes, that is better! Thank you.

2022-12-27 03:31 UTC, KelvinYang0320 commented on docker/README.md
> +   $ docker pull aidudezzz/deepbots:<tag>
Thanks!

2022-12-30 11:12 UTC, tsampazk requested changes
Thanks, just a minor comment. Maybe we could also remove all the `$` from the bash commands so users can straight up use the copy button provided by github UI and then paste directly into their terminal?

![image](https://user-images.githubusercontent.com/27914645/210064310-c0eb278d-1e45-4802-a68f-801072195abb.png)

2022-12-30 11:12 UTC, tsampazk commented on docker/README.md
> +If you wanted, you could replace `aidudezzz/deepbots:0.1.3.dev3` with another name and optionally a tag in the 'name:tag' format.
"You could replace" makes it similar to the previous section.

Also, maybe "add a tag" sounds more complete? Original wording sounds like "optionally *replace* the tag" but it's not that clear.

```suggestion
You could replace `aidudezzz/deepbots:0.1.3.dev3` with another name and optionally add a tag in the 'name:tag' format.
```

2022-12-30 12:56 UTC, KelvinYang0320 commented
> Thanks, just a minor comment. Maybe we could also remove all the $ from the bash commands so users can straight up use the copy button provided by github UI and then paste directly into their terminal?

@tsampazk That's a good point! I have updated this PR. 😄

2023-01-27 10:07 UTC, KelvinYang0320 commented
@tsampazk 
Since we added a requirement.txt, we need to install via 
https://github.com/KelvinYang0320/deepbots/blob/7821c55e4881610897f13dcdd5b85bb905687097/docker/Dockerfile#L27-L29.
I update README accordingly and push [0.1.3.dev4](https://hub.docker.com/layers/aidudezzz/deepbots/0.1.3.dev4/images/sha256-d501bd17ea9379e9c54d9129ce6ffee49a0ba7220894a00d6bc07f2080b5f72d?context=repo) to Docker Hub.

2023-03-05 16:29 UTC, tsampazk requested changes

2023-03-05 16:29 UTC, tsampazk commented on docker/Dockerfile
> +            pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ $branch ; \
I think we can remove the `--index-url...` for test.pypi

2023-03-05 16:29 UTC, tsampazk commented on docker/README.md
> +      * `deepbots==<version>`: Install the specific version of deepbots on [PyPI](https://pypi.org/project/deepbots/) or [TestPyPI](https://test.pypi.org/search/?q=deepbots).
test pypi stuff can also be removed from here.

2023-03-06 07:32 UTC, KelvinYang0320 commented on docker/README.md
> +      * `deepbots==<version>`: Install the specific version of deepbots on [PyPI](https://pypi.org/project/deepbots/) or [TestPyPI](https://test.pypi.org/search/?q=deepbots).
~`dev`: Install from [the dev branch of deepbots on GitHub](https://github.com/aidudezzz/deepbots/tree/dev).~

2023-03-06 07:37 UTC, KelvinYang0320 commented on docker/Dockerfile
> +            pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ $branch ; \
```suggestion
            pip install --index-url https://pypi.org/simple/ $branch ; \
```

2023-03-06 08:55 UTC, tsampazk reviewed
I think that the docker stuff look good now, thank you very much @KelvinYang0320! Maybe also @eakirtas can take a look before we merge it?

2023-06-03 15:10 UTC, tsampazk submitted a review, later dismissed

2023-06-03 16:44 UTC, merged